### PR TITLE
https://github.com/Bunlong/react-screen-capture/issues/10 - Seems to …

### PR DESCRIPTION
**Pull request by vyemialyanchyk**
…break on all screens above 1080p - fixed

### CODE REVIEW

**Comment by vyemialyanchyk** [comment]
fixed

**Comment by vyemialyanchyk** [comment]
fixed

**Comment by vyemialyanchyk** [comment]
could someone please merge and release?

**Comment by gwhizoftv** [comment]
@Bunlong please merge

**Pull request closed without merging**
